# Generated by Django 5.1.7 on 2025-03-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universityapp", "0003_alter_enrollment_updated_at_program_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseunit",
            options={"ordering": ["course", "title"]},
        ),
        migrations.RemoveField(
            model_name="courseunit",
            name="content",
        ),
        migrations.RemoveField(
            model_name="courseunit",
            name="description",
        ),
        migrations.RemoveField(
            model_name="courseunit",
            name="order",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="status",
        ),
        migrations.AddField(
            model_name="courseunit",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="universityapp.lecturer",
            ),
        ),
    ]
