# Generated by Django 5.1.7 on 2025-03-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universityapp",
            "0004_alter_courseunit_options_remove_courseunit_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="courseunit",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="universityapp.faculty",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="courses",
                        through="universityapp.Enrollment",
                        to="universityapp.student",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="universityapp.course",
            ),
        ),
        migrations.AlterField(
            model_name="courseunit",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="universityapp.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="universityapp.course"
            ),
        ),
        migrations.DeleteModel(
            name="Program",
        ),
    ]
