# Generated by Django 5.1.7 on 2025-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universityapp", "0005_alter_assignment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("student", "status"),
                name="unique_active_enrollment",
            ),
        ),
    ]
